# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

skip_screenshots(true)

skip_metadata(true)

force(true)
