name: appstore build CI

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'iOS-yi-iot: Debug/Release'
        default: 'Release'
        required: true
      message:
        description: 'post message as text file to slack'
        required: true
        default: 'New version!'

jobs:
  build:
    name: Running appstore build CI
    runs-on: macOS-SH
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3 # Github action in use (checkout)
        with:
          token: ${{ secrets.IOS_GITHUB_TOKEN }}
          lfs: true

      - name: Building
        run: bundle exec fastlane app configuration:${{ github.event.inputs.configuration }}

      - name: Sending YiIoT build to Slack
        id: message
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.QA_RELEASE_BOT_TOKEN }}
          file_path: build/*.ipa
          channel_id: C0496EGPDEC
          retries: 0
          initial_comment: ${{ github.event.inputs.message }}
        continue-on-error: true
        
      - name: Sending YiIoT dSYM to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.QA_RELEASE_BOT_TOKEN }}
          file_path: build/*.zip
          channel_id: C0496EGPDEC
          retries: 0
        continue-on-error: true
