name: PR automatic build CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    name: Running PR automatic build CI
    runs-on: macOS-SH
    steps:
      - name: Get ticket number
        id: ticket-number
        run: |
          id=$(echo "${{ github.event.pull_request.title }}" | cut -d: -f1)
          if [[ $id != IOTIOS* ]]; then id=""; fi
          echo "::set-output name=TICKET_NUMBER::$id"
        
      - name: Checkout
        uses: actions/checkout@v3 # Github action in use (checkout)
        with:
          token: ${{ secrets.IOS_GITHUB_TOKEN }}
          lfs: true

      - name: Building 
        run: bundle exec fastlane adhoc configuration:Release branch:${{ steps.ticket-number.outputs.TICKET_NUMBER }}
        
      - name: Sending YiIoT build to Slack
        id: message
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.QA_RELEASE_BOT_TOKEN }}
          file_path: build/*.ipa
          channel_id: C0496EGPDEC
          retries: 0
          initial_comment: ${{ github.event.pull_request.title }}
        continue-on-error: true
