name: schedule build CI

on:
  schedule:
    - cron: '0 0 * * 1-6'

jobs:
  nightly:
    name: Running nightly build CI
    runs-on: macOS-SH
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Github action in use (checkout)
        with:
          token: ${{ secrets.IOS_GITHUB_TOKEN }}
          lfs: true

      - name: Building nightly adhoc build
        run: bundle exec fastlane nightlyadhoc

      - name: Sending YiIoT adhoc build to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.QA_RELEASE_BOT_TOKEN }}
          file_path: build/YiIoT-nightly-adhoc-release.ipa
          channel_id: C0496EGPDEC
          retries: 0
        continue-on-error: true
          
      - name: Sending YiIoT dev build to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.QA_RELEASE_BOT_TOKEN }}
          file_path: build/YiIoT-nightly-adhoc-debug.ipa
          channel_id: C0496EGPDEC
          retries: 0
        continue-on-error: true
